### ISSUE TITLE
How to disable Syncing ?

### ISSUE THREAD

**Issue by MarArMar** [anyproto/any-sync-filenode#90]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I find the syncing invasive, I do not want my files stored elsewhere unless I give explicit approval to Anytype

How to disable it ? I looked in many settings and could not find it

### Suggested solution

Add an option to disable syncing

**Comment by fuksman** [comment]
Hi @MarArMar, there is a local-only mode: https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode
